# Generated by Django 5.0.1 on 2024-07-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=254)),
                ('CustomerEmail', models.EmailField(max_length=254)),
                ('ContactNumber', models.IntegerField(max_length=10)),
                ('Date', models.DateField()),
            ],
        ),
    ]
