# Generated by Django 5.0.1 on 2024-07-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ContactNumber',
            field=models.IntegerField(),
        ),
    ]
